name: 'Build a Java function'
description: 'Build a Java function using Gradle'
inputs:
  java_version:
    description: 'The Java version'
    required: false
    default: '11'
  build_command:
    description: 'The command to build the Java project'
    required: false
    default: 'gradle build azureFunctionsPackage -Pprod,azure'
runs:
  using: "composite"
  steps:
    - name: Download Terraform output data
      uses: actions/download-artifact@v2
      with:
        name: terraform-output
    - name: Set environment variables
      run: |
        echo "RESOURCE_GROUP=$(cat terraform-output.json | jq -r .resource_group.value)" >> $GITHUB_ENV
        echo "APPLICATION_CAF_NAME=$(cat terraform-output.json | jq -r .application_caf_name.value)" >> $GITHUB_ENV
      shell: bash
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java_version }}
        check-latest: false
        cache: 'gradle'
    - name: Build with Gradle
      run: |
        ${{ inputs.build_command }} \
        -DfunctionResourceGroup=${{ env.RESOURCE_GROUP }} \
        -DfunctionAppName=${{ env.APPLICATION_CAF_NAME }}
      shell: bash
    - name: Temporarily save package
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: '${{ github.workspace }}/build/azure-functions/${{ env.APPLICATION_CAF_NAME }}/'
        retention-days: 1
