name: 'Build'
description: 'Build a Java project using Maven'
inputs:
  java_version:
    description: 'The Java version'
    required: false
    default: '11'
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java_version }}
        check-latest: false
        cache: 'maven'
    - name: Build with Maven
      run: mvn package -Pprod,azure
      shell: bash
    - name: Temporarily save package
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: '${{ github.workspace }}/target/*.[j,w]ar'
        retention-days: 1
